services:
  cardagon-postgres:
    image: postgres:18
    container_name: cardagon-postgres
    environment:
      POSTGRES_PASSWORD: 5RcBPgUL2IbKYGuE
      POSTGRES_USER: cardagon
      POSTGRES_DB: cardagondb
    ports:
      - "5432:5432"
    volumes:
      - cardagon-pgdata:/var/lib/postgresql

volumes:
  cardagon-pgdata:
