[project]
name = "cardagon-server"
version = "1.0.0"
dependencies = [
  "fastapi[standard]==0.136.3",
  "sqlalchemy==2.0.50",
  "pydantic-settings==2.14.1",
  "passlib==1.7.4",
  "pyjwt==2.13.0",
  "psycopg2-binary==2.9.12",
  "alembic==1.18.4",
  "argon2_cffi==25.1.0",
  "coolname==5.0.0",
  "distinctipy",
]
requires-python = "==3.14.5"


[tool.black]
line-length = 88

[tool.alembic]
script_location = "%(here)s/alembic"
prepend_sys_path = ["."]
