"""add name to games

Revision ID: bd04a8605954
Revises: 47f81029eea1
Create Date: 2026-05-20 14:54:07.740269

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd04a8605954'
down_revision: Union[str, Sequence[str], None] = '47f81029eea1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('games', sa.Column('name', sa.String(length=100), nullable=False, server_default='unnamed game'))
    op.alter_column('games', 'name', server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'name')
    # ### end Alembic commands ###
