"""empty message

Revision ID: 2b37f21175d8
Revises: bd04a8605954
Create Date: 2026-05-21 14:10:04.525804

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b37f21175d8'
down_revision: Union[str, Sequence[str], None] = 'bd04a8605954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_events',
    sa.Column('id', sa.CHAR(length=36), nullable=False),
    sa.Column('game_id', sa.CHAR(length=36), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('turn_number', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=True),
    sa.Column('type', sa.String(length=64), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], name='fk_game_events_game', onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_game_events_user', onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_events_id'), 'game_events', ['id'], unique=False)
    op.alter_column('games', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.add_column('user_game_associations', sa.Column('date_created', sa.DateTime(), nullable=False))
    op.alter_column('user_game_associations', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_game_associations', 'user_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('user_game_associations', 'game_id',
               existing_type=sa.CHAR(length=32),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.alter_column('users', 'id',
               existing_type=sa.CHAR(length=32),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id',
               existing_type=sa.CHAR(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_game_associations', 'game_id',
               existing_type=sa.CHAR(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_game_associations', 'user_id',
               existing_type=sa.CHAR(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.alter_column('user_game_associations', 'id',
               existing_type=sa.CHAR(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_column('user_game_associations', 'date_created')
    op.alter_column('games', 'id',
               existing_type=sa.CHAR(length=36),
               type_=sa.CHAR(length=32),
               existing_nullable=False)
    op.drop_index(op.f('ix_game_events_id'), table_name='game_events')
    op.drop_table('game_events')
    # ### end Alembic commands ###
