"""add color to user_game_associations

Revision ID: d40e0aa76ee2
Revises: a3fa222aed26
Create Date: 2026-05-23 14:46:05.472832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd40e0aa76ee2'
down_revision: Union[str, Sequence[str], None] = 'a3fa222aed26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_associations', sa.Column('color', sa.String(length=7), nullable=False, server_default='#000000'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_game_associations', 'color')
    # ### end Alembic commands ###
